package fit.test_order_service.enums;

public enum EventType {
    CREATE, UPDATE, DELETE, VIEW, VIEW_ALL,RUN, STATUS_CHANGE, ADD_RESULT,
    ADD_ORDER_ITEM, UPDATE_ORDER_ITEM, DELETE_ORDER_ITEM, VIEW_ORDER_ITEM,
    ADD_COMMENT, UPDATE_COMMENT, DELETE_COMMENT, REVIEW_HUMAN, REVIEW_AI,
    PRINT_REQUEST, EXPORT_REQUEST
}