package fit.iam_service.enums;

public enum PrivilegeCode {
    READ_ONLY,
    TEST_ORDER_CREATE, TEST_ORDER_MODIFY, TEST_ORDER_DELETE, TEST_ORDER_REVIEW,
    COMMENT_ADD, COMMENT_MODIFY, COMMENT_DELETE,
    CONFIG_VIEW, CONFIG_CREATE, CONFIG_MODIFY, CONFIG_DELETE,
    USER_VIEW, USER_CREATE, USER_MODIFY, USER_DELETE, USER_LOCK_UNLOCK,
    ROLE_VIEW, ROLE_CREATE, ROLE_UPDATE, ROLE_DELETE,
    EVENT_LOG_VIEW,
    REAGENT_ADD, REAGENT_MODIFY, REAGENT_DELETE,
    INSTRUMENT_ADD, INSTRUMENT_VIEW, INSTRUMENT_ACTIVATE_DEACTIVATE,
    BLOOD_TEST_EXECUTE
}